#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jun 19 09:12:09 EDT 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_4 processing_system7_vip_v1_0_6 lib_pkg_v1_0_2 lib_cdc_v1_0_2 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_iic_v2_0_21 xlconcat_v2_1_1 proc_sys_reset_v5_0_13 util_vector_logic_v2_0_1 xlconstant_v1_1_5 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_18 fifo_generator_v13_2_3 axi_data_fifo_v2_1_17 axi_crossbar_v2_1_19 util_reduced_logic_v2_0_4 smartconnect_v1_0 lib_fifo_v1_0_12 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_20 axi_sg_v4_1_11 axi_dma_v7_1_19 blk_mem_gen_v8_4_2 xbip_utils_v3_0_9 axi_utils_v2_0_5 xbip_pipe_v3_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_5 xbip_bram18k_v3_0_5 mult_gen_v12_0_14 floating_point_v7_0_15 xbip_dsp48_mult_v3_0_5 xbip_dsp48_multadd_v3_0_5 div_gen_v5_1_14 c_reg_fd_v12_0_5 xbip_addsub_v3_0_5 c_addsub_v12_0_12 c_mux_bit_v12_0_5 c_shift_ram_v12_0_12 cmpy_v6_0_16 xfft_v9_1_1 c_gate_bit_v12_0_5 c_compare_v12_0_5 xbip_counter_v3_0_5 c_counter_binary_v12_0_12 c_mux_bus_v12_0_5 viterbi_v9_1_10 xlslice_v1_0_1 fir_compiler_v7_2_11 axi_protocol_converter_v2_1_18 axi_clock_converter_v2_1_17 axi_dwidth_converter_v2_1_18)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_4 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/98af/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/70cf/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_sys_ps7_0/sim/system_sys_ps7_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_21 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/304c/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_axi_iic_main_0/sim/system_axi_iic_main_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_sys_concat_intc_0/sim/system_sys_concat_intc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_sys_rstgen_0/sim/system_sys_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_sys_logic_inv_0/sim/system_sys_logic_inv_0.v" \
    "$ref_dir/../../../../../src/ipshared/17e0/axi_sysid.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_axi.v" \
    "$ref_dir/../../../../../src/ip/system_axi_sysid_0_0/sim/system_axi_sysid_0_0.v" \
    "$ref_dir/../../../../../src/ipshared/72a7/sysid_rom.v" \
    "$ref_dir/../../../../../src/ip/system_rom_sys_0_0/sim/system_rom_sys_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_GND_1_0/sim/system_GND_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/64f4/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_3 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_xbar_0/sim/system_xbar_0.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_addsub.v" \
    "$ref_dir/../../../../../src/ipshared/xilinx/common/ad_data_clk.v" \
    "$ref_dir/../../../../../src/ipshared/xilinx/common/ad_data_in.v" \
    "$ref_dir/../../../../../src/ipshared/xilinx/common/ad_data_out.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_datafmt.v" \
    "$ref_dir/../../../../../src/ipshared/xilinx/common/ad_dcfilter.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_dds.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_dds_1.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_dds_2.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_dds_cordic_pipe.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_dds_sine.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_dds_sine_cordic.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_iqcor.v" \
    "$ref_dir/../../../../../src/ipshared/xilinx/common/ad_mul.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_pnmon.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_pps_receiver.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_rst.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_tdd_control.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/xilinx/axi_ad9361_cmos_if.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/xilinx/axi_ad9361_lvds_if.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361_rx.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361_rx_channel.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361_rx_pnmon.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361_tdd.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361_tdd_if.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361_tx.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361_tx_channel.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_adc_channel.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_adc_common.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_clock_mon.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_dac_channel.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_dac_common.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_delay_cntrl.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_tdd_cntrl.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_xfer_cntrl.v" \
    "$ref_dir/../../../../../src/ipshared/common/up_xfer_status.v" \
    "$ref_dir/../../../../../src/ipshared/6c78/axi_ad9361.v" \
    "$ref_dir/../../../../../src/ip/system_axi_ad9361_0/sim/system_axi_ad9361_0.v" \
    "$ref_dir/../../../../../src/ipshared/common/util_pulse_gen.v" \
    "$ref_dir/../../../../../src/ipshared/2902/util_tdd_sync.v" \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_tdd_sync_0/sim/system_util_ad9361_tdd_sync_0.v" \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_divclk_sel_concat_0/sim/system_util_ad9361_divclk_sel_concat_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_reduced_logic_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/4c94/hdl/util_reduced_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_divclk_sel_0/sim/system_util_ad9361_divclk_sel_0.v" \
    "$ref_dir/../../../../../src/ipshared/3cee/util_clkdiv.v" \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_divclk_0/sim/system_util_ad9361_divclk_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_divclk_reset_0/sim/system_util_ad9361_divclk_reset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/common/ad_mem.v" \
    "$ref_dir/../../../../../src/ipshared/6dc6/util_wfifo.v" \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_adc_fifo_0/sim/system_util_ad9361_adc_fifo_0.v" \
    "$ref_dir/../../../../../src/common/ad_perfect_shuffle.v" \
    "$ref_dir/../../../../../src/ipshared/util_pack_common/pack_ctrl.v" \
    "$ref_dir/../../../../../src/ipshared/util_pack_common/pack_interconnect.v" \
    "$ref_dir/../../../../../src/ipshared/util_pack_common/pack_network.v" \
    "$ref_dir/../../../../../src/ipshared/util_pack_common/pack_shell.v" \
    "$ref_dir/../../../../../src/ipshared/6106/util_cpack2_impl.v" \
    "$ref_dir/../../../../../src/ipshared/6106/util_cpack2.v" \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_adc_pack_0/sim/system_util_ad9361_adc_pack_0.v" \
    "$ref_dir/../../../../../src/ipshared/fb52/sync_bits.v" \
    "$ref_dir/../../../../../src/ipshared/fb52/sync_data.v" \
    "$ref_dir/../../../../../src/ipshared/fb52/sync_event.v" \
    "$ref_dir/../../../../../src/ipshared/fb52/sync_gray.v" \
    "$ref_dir/../../../../../src/ipshared/0d03/address_gray_pipelined.v" \
    "$ref_dir/../../../../../src/ipshared/0d03/address_sync.v" \
    "$ref_dir/../../../../../src/ipshared/0d03/util_axis_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_ad9361_adc_dma_0/sim/system_axi_ad9361_adc_dma_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/225a/2d_transfer.v" \
    "$ref_dir/../../../../../src/ipshared/common/ad_mem_asym.v" \
    "$ref_dir/../../../../../src/ipshared/225a/address_generator.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_burst_memory.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_regmap.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_regmap_request.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_reset_manager.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_resize_dest.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_resize_src.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_response_manager.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac_transfer.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_register_slice.v" \
    "$ref_dir/../../../../../src/ipshared/225a/data_mover.v" \
    "$ref_dir/../../../../../src/ipshared/225a/dest_axi_mm.v" \
    "$ref_dir/../../../../../src/ipshared/225a/dest_axi_stream.v" \
    "$ref_dir/../../../../../src/ipshared/225a/dest_fifo_inf.v" \
    "$ref_dir/../../../../../src/ipshared/225a/request_arb.v" \
    "$ref_dir/../../../../../src/ipshared/225a/request_generator.v" \
    "$ref_dir/../../../../../src/ipshared/225a/response_generator.v" \
    "$ref_dir/../../../../../src/ipshared/225a/response_handler.v" \
    "$ref_dir/../../../../../src/ipshared/225a/splitter.v" \
    "$ref_dir/../../../../../src/ipshared/225a/src_axi_mm.v" \
    "$ref_dir/../../../../../src/ipshared/225a/src_axi_stream.v" \
    "$ref_dir/../../../../../src/ipshared/225a/src_fifo_inf.v" \
    "$ref_dir/../../../../../src/ipshared/225a/axi_dmac.v" \
    "$ref_dir/../../../../../src/ip/system_axi_ad9361_adc_dma_0/sim/system_axi_ad9361_adc_dma_0.v" \
    "$ref_dir/../../../../../src/ipshared/a1d7/util_rfifo.v" \
    "$ref_dir/../../../../../src/ip/system_axi_ad9361_dac_fifo_0/sim/system_axi_ad9361_dac_fifo_0.v" \
    "$ref_dir/../../../../../src/ipshared/96cf/util_upack2_impl.v" \
    "$ref_dir/../../../../../src/ipshared/96cf/util_upack2.v" \
    "$ref_dir/../../../../../src/ip/system_util_ad9361_dac_upack_0/sim/system_util_ad9361_dac_upack_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_ad9361_dac_dma_0/sim/system_axi_ad9361_dac_dma_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_ad9361_dac_dma_0/sim/system_axi_ad9361_dac_dma_0.v" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/sim/bd_31bd.v" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_0/sim/bd_31bd_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/sim/bd_31bd_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/979d/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../../src/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_2/sim/bd_31bd_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_3/sim/bd_31bd_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/9ade/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_4/sim/bd_31bd_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/sim/bd_31bd_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/sim/bd_31bd_sawn_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/sim/bd_31bd_swn_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/sim/bd_31bd_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/sim/bd_31bd_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_10/sim/bd_31bd_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp1_interconnect_0/sim/system_axi_hp1_interconnect_0.v" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/sim/bd_c0fd.v" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/sim/bd_c0fd_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/sim/bd_c0fd_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/sim/bd_c0fd_s00mmu_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/sim/bd_c0fd_s00tr_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/sim/bd_c0fd_s00sic_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/sim/bd_c0fd_s00a2s_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/sim/bd_c0fd_sarn_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/sim/bd_c0fd_srn_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/sim/bd_c0fd_m00s2a_0.sv" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/sim/bd_c0fd_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_axi_hp2_interconnect_0/sim/system_axi_hp2_interconnect_0.v" \
    "$ref_dir/../../../../../src/ipshared/0a57/axi_xcvrlb_1.v" \
    "$ref_dir/../../../../../src/ipshared/util_adxcvr/util_adxcvr_xch.v" \
    "$ref_dir/../../../../../src/ipshared/0a57/axi_xcvrlb.v" \
    "$ref_dir/../../../../../src/ip/system_axi_pz_xcvrlb_0/sim/system_axi_pz_xcvrlb_0.v" \
    "$ref_dir/../../../../../src/ipshared/0d4f/axi_gpreg_clock_mon.v" \
    "$ref_dir/../../../../../src/ipshared/0d4f/axi_gpreg_io.v" \
    "$ref_dir/../../../../../src/ipshared/0d4f/axi_gpreg.v" \
    "$ref_dir/../../../../../src/ip/system_axi_gpreg_0/sim/system_axi_gpreg_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_12 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/544a/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_20 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/dfb3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_11 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/efa7/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_19 $vhdlan_opts \
    "$ref_dir/../../../../../src/ipshared/09b0/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_axi_dma_0_0/sim/system_axi_dma_0_0.vhd" \
    "$ref_dir/../../../../../src/ip/system_axi_dma_1_0/sim/system_axi_dma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_xbar_1/sim/system_xbar_1.v" \
    "$ref_dir/../../../../../src/ip/system_xbar_2/sim/system_xbar_2.v" \
    "$ref_dir/../../../../../src/ip/system_xbar_3/sim/system_xbar_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/deinter_lut/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/deinter_lut/sim/deinter_lut.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/0da8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/ec8e/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/a04b/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_15 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/a054/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_mult_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/9f55/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/b226/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work div_gen_v5_1_14 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/d5ca/hdl/div_gen_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/div_gen_div_gen_0_0/sim/div_gen_div_gen_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/rot_lut/sim/rot_lut.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work c_reg_fd_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cmpy_v6_0_16 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xfft_v9_1_1 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/xfft_v9/sim/xfft_v9.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_compare_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_compare_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bus_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/c_mux_bus_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work viterbi_v9_1_10 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/hdl/viterbi_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/viterbi_v7_0/sim/viterbi_v7_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/div_gen_xlslice_0_0/sim/div_gen_xlslice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/complex_multiplier/sim/complex_multiplier.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/src/atan_lut/sim/atan_lut.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/bits_to_bytes.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/calc_mean.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/complex_mult.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/complex_to_mag.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/complex_to_mag_sq.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/crc32.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/deinterleave.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/delayT.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/delay_sample.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/demodulate.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/descramble.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/div_gen.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/divider.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/dot11.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/equalizer.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/ht_sig_crc.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/moving_avg.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/ofdm_decoder.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/openofdm_rx_s_axi.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/phase.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/ram_2port.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/rotate.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/stage_mult.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/sync_long.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/sync_short.v" \
    "$ref_dir/../../../../../src/ipshared/43ce/src/openofdm_rx.v" \
    "$ref_dir/../../../../../src/ip/system_openofdm_rx_0_0/sim/system_openofdm_rx_0_0.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/axi_fifo_bram.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/bimpy.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/bitreverse.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/butterfly.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/convenc.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/convround.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/crc32_tx.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/dot11_tx.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/hwbfly.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/ifftmain.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/ifftstage.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/laststage.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/long_preamble_rom.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/longbimpy.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/modulation.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/openofdm_tx_s_axi.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/punc_interlv_lut.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/qtrstage.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/ram_2port.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/ram_simo.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/short_preamble_rom.v" \
    "$ref_dir/../../../../../src/ipshared/8f91/src/openofdm_tx.v" \
    "$ref_dir/../../../../../src/ip/system_openofdm_tx_0_0/sim/system_openofdm_tx_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_sys_rstgen1_0/sim/system_sys_rstgen1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_xlslice_0_0/sim/system_xlslice_0_0.v" \
    "$ref_dir/../../../../../src/ip/system_xlslice_1_0/sim/system_xlslice_1_0.v" \
    "$ref_dir/../../../../../src/ip/system_xpu_0_0/src/fifo8_1clk_dep64_fifo_generator_0_0/sim/fifo8_1clk_dep64_fifo_generator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fir_compiler_v7_2_11 $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_xpu_0_0/ipshared/3697/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_xpu_0_0/src/mv_avg32_fir_compiler_0_0/sim/mv_avg32_fir_compiler_0_0.vhd" \
    "$ref_dir/../../../../../src/ip/system_xpu_0_0/src/mv_avg128_fir_compiler_0_0/sim/mv_avg128_fir_compiler_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/936d/src/cca.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/csma_ca.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/dc_rm.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/fifo8_1clk_dep64.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/fifo8_delay64.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/iq_abs_avg.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/iq_rssi_to_db.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/mv_avg128.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/mv_avg32.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/n_sym_len14_pkt.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/phy_rx_parse.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/pkt_filter_ctl.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/rssi.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/time_slice_gen.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/tsf_timer.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/tx_control.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/tx_on_detection.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/xpu_s_axi.v" \
    "$ref_dir/../../../../../src/ipshared/936d/src/xpu.v" \
    "$ref_dir/../../../../../src/ip/system_xpu_0_0/sim/system_xpu_0_0.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/src/fifo64_1clk_dep512_fifo_generator_0_0/sim/fifo64_1clk_dep512_fifo_generator_0_0.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/src/fifo32_1clk_dep512_fifo_generator_0_0/sim/fifo32_1clk_dep512_fifo_generator_0_0.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/src/fifo64_1clk_dep64_fifo_generator_0_0/sim/fifo64_1clk_dep64_fifo_generator_0_0.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/src/fifo64_1clk_fifo_generator_0_0/sim/fifo64_1clk_fifo_generator_0_0.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_i_p0n5n10n15n20MHz.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_mac_muladd_16s_8s_24s_24_3_1.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_mac_mulsub_16s_8s_24s_24_3_1.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_mul_mul_16s_8s_24_3_1.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc_q_p0n5n10n15n20MHz.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/ipshared/77fc/hdl/verilog/mixer_duc.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/src/duc_bank_core_mixer_duc_0_0/sim/duc_bank_core_mixer_duc_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/src/duc_bank_core_fir_compiler_0_0/sim/duc_bank_core_fir_compiler_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/src/fifo32_2clk_dep32_fifo_generator_0_0/sim/fifo32_2clk_dep32_fifo_generator_0_0.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/dac_intf.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/duc_bank_core.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/fifo32_1clk_dep512.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/fifo32_2clk_dep32.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/fifo64_1clk.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/fifo64_1clk_dep512.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/fifo64_1clk_dep64.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_bit_intf.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_interrupt_selection.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_intf_m_axis.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_intf_pl_to_m_axis.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_intf_s_axi.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_intf_s_axis.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_iq_intf.v" \
    "$ref_dir/../../../../../src/ipshared/3328/src/tx_intf.v" \
    "$ref_dir/../../../../../src/ip/system_tx_intf_0_0/sim/system_tx_intf_0_0.v" \
    "$ref_dir/../../../../../src/ip/system_rx_intf_0_0/src/fifo32_1clk_dep32_fifo_generator_0_0/sim/fifo32_1clk_dep32_fifo_generator_0_0.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/adc_intf.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/byte_to_word_fcs_sn_insert.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/fifo32_1clk_dep32.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/rx_intf_m_axis.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/rx_intf_pl_to_m_axis.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/rx_intf_s_axi.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/rx_intf_s_axis.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/rx_iq_intf.v" \
    "$ref_dir/../../../../../src/ipshared/f100/src/rx_intf.v" \
    "$ref_dir/../../../../../src/ip/system_rx_intf_0_0/sim/system_rx_intf_0_0.v" \
    "$ref_dir/../../../../../src/sim/system.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/7a04/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/693a/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ipshared/0815/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../../src/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../../src/ipshared/225a" +incdir+"$ref_dir/../../../../../src/ipshared/979d/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../../src/ipshared/43ce/src" +incdir+"$ref_dir/../../../../../src/ipshared/936d/src" +incdir+"$ref_dir/../../../../../src/ip/system_sys_ps7_0" +incdir+"$ref_dir/../../../../../src/ipshared/3328/src" +incdir+"$ref_dir/../../../../../src/ipshared/f100/src" +incdir+"/opt/Xilinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../../src/ip/system_auto_us_0/sim/system_auto_us_0.v" \
    "$ref_dir/../../../../../src/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../../../src/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \
    "$ref_dir/../../../../../src/ip/system_auto_us_1/sim/system_auto_us_1.v" \
    "$ref_dir/../../../../../src/ip/system_auto_pc_3/sim/system_auto_pc_3.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/sdr/workspace/ns/openwifi/openwifi-hw/boards/adrv9361z7035/openwifi_adrv9361z7035/openwifi_adrv9361z7035.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
