# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/viterbi_v7_0/viterbi_v7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==viterbi_v7_0 || ORIG_REF_NAME==viterbi_v7_0} -quiet] -quiet

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/deinter_lut/deinter_lut.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==deinter_lut || ORIG_REF_NAME==deinter_lut} -quiet] -quiet

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/div_gen_xlslice_0_0/div_gen_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_xlslice_0_0 || ORIG_REF_NAME==div_gen_xlslice_0_0} -quiet] -quiet

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/div_gen_div_gen_0_0/div_gen_div_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==div_gen_div_gen_0_0 || ORIG_REF_NAME==div_gen_div_gen_0_0} -quiet] -quiet

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/complex_multiplier/complex_multiplier.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==complex_multiplier || ORIG_REF_NAME==complex_multiplier} -quiet] -quiet

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/xfft_v9/xfft_v9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_v9 || ORIG_REF_NAME==xfft_v9} -quiet] -quiet

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/atan_lut/atan_lut.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==atan_lut || ORIG_REF_NAME==atan_lut} -quiet] -quiet

# IP: /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/rot_lut/rot_lut.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rot_lut || ORIG_REF_NAME==rot_lut} -quiet] -quiet
