# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z035ifbg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sdr/workspace/ns/openwifi/openwifi-hw/boards/adrv9361z7035/openwifi_adrv9361z7035/openwifi_adrv9361z7035.tmp/openofdm_rx_v1_0_project/openofdm_rx_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/sdr/workspace/ns/openwifi/openwifi-hw/boards/adrv9361z7035/openwifi_adrv9361z7035/openwifi_adrv9361z7035.tmp/openofdm_rx_v1_0_project/openofdm_rx_v1_0_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/sdr/workspace/ns/openwifi/openwifi-hw/adi-hdl/library
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/high
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/sdr/workspace/ns/openwifi/openwifi-hw/boards/adrv9361z7035/openwifi_adrv9361z7035/openwifi_adrv9361z7035.tmp/openofdm_rx_v1_0_project/openofdm_rx_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/deinter_lut.coe
add_files /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/rot_lut.coe
add_files /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/atan_lut.coe
read_verilog {
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/common_defs.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/common_params.v
}
set_property file_type "Verilog Header" [get_files /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/common_defs.v]
set_property file_type "Verilog Header" [get_files /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/common_params.v]
read_verilog -library "" {
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/bits_to_bytes.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/calc_mean.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/complex_mult.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/complex_to_mag.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/complex_to_mag_sq.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/crc32.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/deinterleave.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/delayT.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/delay_sample.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/demodulate.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/descramble.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/div_gen.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/divider.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/dot11.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/equalizer.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/ht_sig_crc.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/moving_avg.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/ofdm_decoder.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/openofdm_rx_s_axi.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/phase.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/ram_2port.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/rotate.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/stage_mult.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/sync_long.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/sync_short.v
  /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/openofdm_rx.v
}
read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/viterbi_v7_0/viterbi_v7_0.xci

read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/deinter_lut/deinter_lut.xci

read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/div_gen_xlslice_0_0/div_gen_xlslice_0_0.xci

read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/div_gen_div_gen_0_0/div_gen_div_gen_0_0.xci

read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/complex_multiplier/complex_multiplier.xci

read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/xfft_v9/xfft_v9.xci

read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/atan_lut/atan_lut.xci

read_ip -quiet /home/sdr/workspace/ns/openwifi/openwifi-hw/ip_repo/common/openofdm_rx/src/rot_lut/rot_lut.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top openofdm_rx -part xc7z035ifbg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef openofdm_rx.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file openofdm_rx_utilization_synth.rpt -pb openofdm_rx_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
