#set_clock_groups -asynchronous -group [get_clocks [list i_system_wrapper/system_i/util_ad9361_divclk/inst/clk_out]] -group [get_clocks [list i_system_wrapper/system_i/sys_ps8/inst/pl_clk2]]
#set_false_path -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/util_ad9361_divclk/inst/clk_divide_sel_0/O]] -to [get_clocks clk_pl_2]
#set_false_path -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/util_ad9361_divclk/inst/clk_divide_sel_1/O]] -to [get_clocks clk_pl_2]

## relax cross rf and bb domain control of adc_intf
#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_count_reg/C] -to [get_pins {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/wren_count_reg[0]/R}]
#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_count_reg/C] -to [get_pins {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/wren_count_reg[1]/R}]
#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_count_reg/C] -to [get_pins {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/wren_count_reg[2]/R}]
#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_count_reg/C] -to [get_pins {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/wren_count_reg[3]/R}]

#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/fifo32_2clk_dep32_i/fifo_generator_0/U0/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gl0.wr/gwas.wsts/ram_full_i_reg/C] -to [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/FULL_internal_in_bb_domain_reg/D]

#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_count_reg/C] -to [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_decimate_reg_reg/D]
#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_count_reg_replica/C] -to [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_decimate_reg_reg/D]
#set_false_path -from [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_count_reg_replica_1/C] -to [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_decimate_reg_reg/D]

#set_false_path -from [get_pins i_system_wrapper/system_i/util_ad9361_divclk/inst/clk_divide_sel_0/O] -to [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_clk_in_bb_domain_reg/D]
#set_false_path -from [get_pins i_system_wrapper/system_i/util_ad9361_divclk/inst/clk_divide_sel_1/O] -to [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_clk_in_bb_domain_reg/D]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_clk_in_bb_domain_reg/C]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_clk_in_bb_domain_reg/D]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_clk_in_bb_domain_reg/Q]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_clk_in_bb_domain_reg/R]

#set_false_path -from [get_pins i_system_wrapper/system_i/util_ad9361_adc_pack/inst/i_cpack/packed_fifo_wr_en_reg/C] -to [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_in_bb_domain_reg/D]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_in_bb_domain_reg/C]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_in_bb_domain_reg/D]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_in_bb_domain_reg/Q]
#set_false_path -through [get_pins i_system_wrapper/system_i/openwifi_ip/rx_intf_0/inst/adc_intf_i/adc_valid_in_bb_domain_reg/R]

# relax cross rf and bb domain control of dac_intf
set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_src_sel/syncstages_ff_reg[3][0]/C}]
# set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_src_sel/syncstages_ff_reg[3][0]/D}]
# set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_src_sel/syncstages_ff_reg[3][0]/Q}]
# set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_src_sel/syncstages_ff_reg[3][0]/R}]

set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_ant_flag/syncstages_ff_reg[3][0]/C}]
# set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_ant_flag/syncstages_ff_reg[3][0]/D}]
# set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_ant_flag/syncstages_ff_reg[3][0]/Q}]
# set_false_path -through [get_pins {i_system_wrapper/system_i/openwifi_ip/tx_intf_0/inst/dac_intf_i/xpm_cdc_array_single_inst_ant_flag/syncstages_ff_reg[3][0]/R}]

connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_control_i/tx_control_state[0]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_control_i/tx_control_state[1]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_control_i/tx_control_state[2]}]]


connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_FCLK_CLK2]]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK2]

set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[11]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[15]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[17]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[19]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[13]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[21]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[23]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[25]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[27]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[9]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[8]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[15]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[9]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[8]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[11]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[13]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[17]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[19]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[21]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[23]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[25]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[27]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[29]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[31]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[29]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[31]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[10]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[12]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[24]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[26]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[20]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[22]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[14]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[16]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[18]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[14]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[10]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[12]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[16]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[18]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[20]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[22]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[24]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[26]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[28]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[30]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[28]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[30]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[2]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[7]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[0]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[1]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[12]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[14]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[16]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[18]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[28]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[30]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[31]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[29]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[19]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[17]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[15]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[13]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[26]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[27]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[24]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[25]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[22]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[23]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[20]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[21]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[3]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[4]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[5]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[6]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[8]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[9]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[10]}]
set_property MARK_DEBUG true [get_nets {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[11]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/sys_ps7/inst/FCLK_CLK2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/equalizer_inst/state[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/equalizer_inst/state[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/equalizer_inst/state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ofdm_decoder_inst/deinterleave_inst/state[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ofdm_decoder_inst/deinterleave_inst/state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[0]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[1]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[2]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[3]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[4]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[5]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[6]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[7]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[8]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[9]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[10]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[11]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[12]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[13]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[14]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[15]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[16]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[17]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[18]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[19]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[20]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[21]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[22]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[23]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[24]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[25]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[26]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[27]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[28]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[29]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[30]} {i_system_wrapper/system_i/openwifi_ip/IQ_Adder_0/iq_strOut[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sync_long_inst/state[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sync_long_inst/state[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sync_long_inst/state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_count_total[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 24 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[15]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[16]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[17]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[18]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[19]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[20]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[21]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[22]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig1[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 24 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[15]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[16]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[17]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[18]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[19]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[20]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[21]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[22]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_sig2[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/old_state[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/old_state[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/old_state[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/old_state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_len_total[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 8 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_rate[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[15]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[16]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[17]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[18]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[19]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[20]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[21]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[22]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[23]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[24]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[25]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[26]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[27]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[28]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[29]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[30]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 24 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[3]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[4]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[5]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[6]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[7]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[8]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[9]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[10]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[11]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[12]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[13]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[14]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[15]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[16]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[17]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[18]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[19]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[20]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[21]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[22]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/signal_bits[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 4 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/state[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/state[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/state[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 4 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/status_code[0]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/status_code[1]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/status_code[2]} {i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/status_code[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[0]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[1]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[2]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[3]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[4]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[5]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[6]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[7]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[8]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[9]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[10]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[11]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[12]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[13]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[14]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[15]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[16]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[17]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[18]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[19]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[20]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[21]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[22]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[23]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[24]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[25]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[26]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[27]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[28]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[29]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[30]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 32 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[0]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[1]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[2]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[3]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[4]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[5]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[6]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[7]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[8]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[9]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[10]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[11]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[12]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[13]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[14]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[15]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[16]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[17]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[18]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[19]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[20]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[21]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[22]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[23]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[24]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[25]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[26]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[27]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[28]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[29]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[30]} {i_system_wrapper/system_i/openwifi_ip/rx_intf_0/sample_2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 14 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[0]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[1]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[2]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[3]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[4]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[5]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[6]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[7]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[8]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[9]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[10]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[11]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[12]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 14 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[0]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[1]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[2]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[3]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[4]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[5]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[6]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[7]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[8]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[9]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[10]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[11]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[12]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 14 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[0]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[1]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[2]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[3]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[4]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[5]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[6]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[7]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[8]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[9]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[10]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[11]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[12]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/bb_rf_delay_count_top_scale_plus1[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 8 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[0]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[1]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[2]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[3]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[4]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[5]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[6]} {i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/gpio_status[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/byte_out_strobe]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/demod_is_ongoing]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/fcs_ok]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/fcs_out_strobe]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/ht_unsupport]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/phy_tx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/phy_tx_started]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_begin]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_header_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_header_valid_strobe]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/pkt_ht]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/pulse_tx_bb_end]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/pulse_tx_bb_start]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/sample_in_strobe]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/search_indication]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list i_system_wrapper/system_i/openwifi_ip/openofdm_rx_0/inst/dot11_i/soft_decoding]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/tx_bb_is_ongoing]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/tx_bb_is_ongoing_internal]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/tx_iq_fifo_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/tx_iq_fifo_empty_reg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/tx_iq_running]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list i_system_wrapper/system_i/openwifi_ip/xpu_0/inst/tx_on_detection_i/tx_rf_is_ongoing]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK2]
